'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("movieinfoplus.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property arrow_small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bluebar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bluebar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bspb1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bspb1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property emptystar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("emptystar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property f2s0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f2s0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property f2s10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f2s10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property f2s2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f2s2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property f2s8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f2s8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property folder_32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property front() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("front", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fullstar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fullstar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property green_check() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("green_check", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property green_check_gainsboro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("green_check_gainsboro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property green_check1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("green_check1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property halfstar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("halfstar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property imdb_32x25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imdb_32x25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property imdb_32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imdb_32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property imp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property impawards() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("impawards", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mip_splash_jive() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mip_splash_jive", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mip_splash_jive_actual() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mip_splash_jive_actual", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property movieinfoplus_ap() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("movieinfoplus_ap", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property movieinfoplussplash() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("movieinfoplussplash", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mymovies() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mymovies", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property myshows() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("myshows", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mytunes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mytunes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property paypal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("paypal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ph() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ph", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property poster() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("poster", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property precachestarting() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("precachestarting", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property questionmark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("questionmark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property questionmark_gainsboro_jpb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("questionmark_gainsboro.jpb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property red_x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("red_x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property red_x_gainsboro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("red_x_gainsboro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property red_x1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("red_x1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property refresh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("refresh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property refresh24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("refresh24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property search_32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search_32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property small_movieroll_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("small_movieroll_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property spb1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spb1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tag() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tag", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tmdb_32x25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tmdb_32x25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tpb1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tpb1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tv_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tv_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tv_icon32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tv_icon32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tv_wide_example() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tv_wide_example", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tvbgExample() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tvbgExample", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tvbgExample2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tvbgExample2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tvposterexample() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tvposterexample", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property update_refresh_32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("update_refresh_32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property update_shows() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("update-shows", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
